## AI in Enterprise (AIDI - 2004 - 02)

In [1]:
# Please use the xgboost version "0.80" for this problem. 

!pip install xgboost==0.80

     |████████████████████████████████| 15.8 MB 185 kB/s 
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90


#### <font color='black'>LAB Assignment #4 - Heroku</font>

**Submitted By : Jugnu Shefin**  
**Student No: 100814025**

**<font color='blue'>Independent Variables:</font>**  
• Weight  
• Length1   
• Length2   
• Length3    
• Height    
• Width    

**<font color='blue'>Dependent Variable:</font>**   
• Species 

Note: The Fish market dataset used in this analysis is from kaggle from the link - https://www.kaggle.com/aungpyaeap/fish-market. The code used is either a direct copy or a modification of the code provided as part of the Artificial Intelligence for Design and Inplementation graduate certificate at Durham College.

### Business Problem Description

Mr.Huges is interested in creating XGBoost model using **Fish.csv** dataset. 

The goal of the analysis is to create a XGBoost model which would be able to use attributes such as Weight, Length1, Length2, Length3, Height and Width to predict the fish Species and evaluate and understand the classification report results accuracy score and confusion matrix for XGBoost model.   

### Feature Engineering


In [2]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

In [3]:
# Load the dataset
df = pd.read_csv("/content/Fish.csv")

In [4]:
# Random display 10 datapoints.
df.sample(10)

Species  Weight  Length1  Length2  Length3   Height   Width
72       Perch     5.9      7.5      8.4      8.8   2.1120  1.4080
91       Perch   130.0     20.5     22.5     24.0   5.8560  3.6240
103      Perch   260.0     25.4     27.5     28.9   7.1672  4.3350
132       Pike   430.0     35.5     38.0     40.5   7.2900  4.5765
76       Perch    70.0     15.7     17.4     18.5   4.5880  2.9415
154      Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
56   Whitefish   270.0     24.1     26.5     29.3   8.1454  4.2485
119      Perch   850.0     36.9     40.0     42.3  11.9286  7.1064
29       Bream  1000.0     33.5     37.0     42.6  18.9570  6.6030
38       Roach    87.0     18.2     19.8     22.2   5.6166  3.1746

In [5]:
# View dimensions of dataset
df.shape

(159, 7)

In [6]:
# Description of the dataframe.
df.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [7]:
# Check the data type of each column
df.dtypes

Species     object
Weight     float64
Length1    float64
Length2    float64
Length3    float64
Height     float64
Width      float64
dtype: object

**Summary of variables**  
There are 7 variables in the dataset. All the variables are of continuous data type.  
These are given by Weight, Length1, Length2, Length3, Height and Width.  
Species is the target variable. It is categorical data type.

In [8]:
# Check missing values in variables

df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

There are no missing values in the dataset.

In [9]:
# Define Features and Target variable.

X = df.drop(['Species'], axis=1)

y = df['Species']

In [10]:
# Feature scaling.

scaler = MinMaxScaler()
 
X_scaled = scaler.fit_transform(X.to_numpy())

X_scaled = pd.DataFrame(X_scaled, columns=['Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width'])

X_scaled.sample(10)

Weight   Length1   Length2   Length3    Height     Width
88   0.078788  0.242718  0.247273  0.248311  0.254321  0.349205
37   0.047273  0.194175  0.189091  0.209459  0.223303  0.261728
7    0.236364  0.390291  0.392727  0.442568  0.635084  0.513419
35   0.024242  0.104854  0.103636  0.125000  0.140394  0.172023
158  0.012061  0.122330  0.120000  0.125000  0.069872  0.117219
127  0.606061  0.652427  0.647273  0.638514  0.624566  0.923010
123  0.666667  0.611650  0.610909  0.604730  0.642641  0.820478
40   0.000000  0.223301  0.220000  0.236486  0.275519  0.324763
81   0.051515  0.207767  0.210909  0.206081  0.194653  0.243065
122  0.496970  0.574757  0.574545  0.569257  0.545987  0.786874

In [11]:
# Split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [12]:
# Check the shape of X_train and X_test

X_train.shape, X_test.shape

((119, 6), (40, 6))

### Model training

In [13]:
# Model training.

import xgboost as xgb

classifier = xgb.XGBClassifier()

classifier.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [14]:
# Model evaluation.

from sklearn.metrics import accuracy_score

y_pred = classifier.predict(X_test)

print("Accuracy Score:", accuracy_score(y_test, y_pred))

Accuracy Score: 0.775


In [18]:
# Print the Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[11  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0  9  0  3  0  0]
 [ 0  0  1  3  0  0  0]
 [ 0  0  2  0  1  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  1  2  0  0  0  0]]


In [19]:
# Classification_report

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       Bream       1.00      1.00      1.00        11
      Parkki       0.67      1.00      0.80         2
       Perch       0.64      0.75      0.69        12
        Pike       1.00      0.75      0.86         4
       Roach       0.25      0.33      0.29         3
       Smelt       1.00      1.00      1.00         5
   Whitefish       0.00      0.00      0.00         3

    accuracy                           0.78        40
   macro avg       0.65      0.69      0.66        40
weighted avg       0.74      0.78      0.75        40



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
# Save model

import pickle

file_name = "model.pkl"
pickle.dump(classifier, open(file_name, "wb"))

In [21]:
# Load model

with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

In [22]:
# Custom prediction.
input_data = [0.1,0.2,0.3,0.4,0.5,0.6]

# Convert input array to pandas dataframe and predict.
input_df = pd.DataFrame([input_data], columns=["Weight", "Length1", "Length2", "Length3", "Height", "Width"])
result = model.predict(input_df)
print("Output:", result[0])

Output: Smelt
