## AI in Enterprise (AIDI - 2004 - 02)

In [ ]:
# Please use the xgboost version "0.80" for this problem. 

# !pip install xgboost==0.80

     |████████████████████████████████| 15.8 MB 192 kB/s 
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90


#### <font color='black'>LAB Assignment #4 - Heroku</font>

**Submitted By : Jugnu Shefin**  
**Student No: 100814025**

**<font color='blue'>Independent Variables:</font>**  
• Weight  
• Length1   
• Length2   
• Length3    
• Height    
• Width    

**<font color='blue'>Dependent Variable:</font>**   
• Species 

Note: The Fish market dataset used in this analysis is from kaggle from the link - https://www.kaggle.com/aungpyaeap/fish-market. The code used is either a direct copy or a modification of the code provided as part of the Artificial Intelligence for Design and Inplementation graduate certificate at Durham College.

### Business Problem Description

Mr.Huges is interested in creating XGBoost model using **Fish.csv** dataset. 

The goal of the analysis is to create a XGBoost model which would be able to use attributes such as Weight, Length1, Length2, Length3, Height and Width to predict the fish Species and evaluate and understand the classification report results accuracy score and confusion matrix for XGBoost model.   

### Feature Engineering


In [1]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

In [2]:
# Load the dataset
df = pd.read_csv("/content/Fish.csv")

In [4]:
# Random display 10 datapoints.
df.sample(10)

Species  Weight  Length1  Length2  Length3   Height   Width
100   Perch   197.0     23.5     25.6     27.0   6.5610  4.2390
33    Bream   975.0     37.4     41.0     45.9  18.6354  6.7473
97    Perch   145.0     22.0     24.0     25.5   6.3750  3.8250
142    Pike  1600.0     56.0     60.0     64.0   9.6000  6.1440
131    Pike   300.0     34.8     37.3     39.8   6.2884  4.0198
22    Bream   620.0     31.5     34.5     39.7  15.5227  5.2801
52    Roach   290.0     24.0     26.0     29.2   8.8768  4.4968
106   Perch   250.0     25.9     28.0     29.4   7.8204  4.2042
29    Bream  1000.0     33.5     37.0     42.6  18.9570  6.6030
124   Perch  1000.0     39.8     43.0     45.2  11.9328  7.2772

In [5]:
# View dimensions of dataset
df.shape

(159, 7)

In [6]:
# Description of the dataframe.
df.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [7]:
# Check the data type of each column
df.dtypes

Species     object
Weight     float64
Length1    float64
Length2    float64
Length3    float64
Height     float64
Width      float64
dtype: object

**Summary of variables**  
There are 7 variables in the dataset. All the variables are of continuous data type.  
These are given by Weight, Length1, Length2, Length3, Height and Width.  
Species is the target variable. It is categorical data type.

In [8]:
# Check missing values in variables

df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

There are no missing values in the dataset.

In [9]:
# Define Features and Target variable.

X = df.drop(['Species'], axis=1)

y = df['Species']

In [10]:
# Feature scaling.

scaler = MinMaxScaler()
 
X_scaled = scaler.fit_transform(X.to_numpy())

X_scaled = pd.DataFrame(X_scaled, columns=['Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width'])

X_scaled.sample(10)

Weight   Length1   Length2   Length3    Height     Width
83   0.069697  0.223301  0.229091  0.231419  0.243148  0.318547
67   0.103030  0.223301  0.223636  0.243243  0.445051  0.333051
108  0.193939  0.394175  0.392727  0.385135  0.341711  0.524921
73   0.019394  0.097087  0.096364  0.099662  0.104454  0.134134
128  0.121212  0.436893  0.434545  0.439189  0.222862  0.328146
20   0.348485  0.462136  0.465455  0.518581  0.777782  0.637390
34   0.575758  0.592233  0.592727  0.636824  0.922600  0.750296
32   0.560606  0.557282  0.565455  0.616554  0.988229  0.803747
110  0.336970  0.475728  0.474545  0.467905  0.494997  0.752692
113  0.424242  0.514563  0.501818  0.498311  0.515463  0.802492

In [11]:
# Split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [14]:
# Check the shape of X_train and X_test

X_train.shape, X_test.shape

((119, 6), (40, 6))

### Model training

In [15]:
# Model training.

import xgboost as xgb

classifier = xgb.XGBClassifier()

classifier.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [16]:
# Model evaluation.

from sklearn.metrics import accuracy_score

y_pred = classifier.predict(X_test)

print("Accuracy Score:", accuracy_score(y_test, y_pred))

Accuracy Score: 0.775


In [17]:
# Save model

import pickle

file_name = "model.pkl"
pickle.dump(classifier, open(file_name, "wb"))

In [18]:
# Load model

with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

In [19]:
# Custom prediction.
input_data = [0.1,0.2,0.3,0.4,0.5,0.6]

# Convert input array to pandas dataframe and predict.
input_df = pd.DataFrame([input_data], columns=["Weight", "Length1", "Length2", "Length3", "Height", "Width"])
result = model.predict(input_df)
print("Output:", result[0])

Output: Smelt


### Confusion Matrix

In [20]:
# Print the Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[11  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0  9  0  3  0  0]
 [ 0  0  1  3  0  0  0]
 [ 0  0  2  0  1  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  1  2  0  0  0  0]]


In [21]:
# Accuracy Score

accuracy_score(y_test, y_pred)

0.775

### Classification_report

In [22]:
# Classification_report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       Bream       1.00      1.00      1.00        11
      Parkki       0.67      1.00      0.80         2
       Perch       0.64      0.75      0.69        12
        Pike       1.00      0.75      0.86         4
       Roach       0.25      0.33      0.29         3
       Smelt       1.00      1.00      1.00         5
   Whitefish       0.00      0.00      0.00         3

    accuracy                           0.78        40
   macro avg       0.65      0.69      0.66        40
weighted avg       0.74      0.78      0.75        40



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
